export const COUNTER_CHANGE = 'COUNTER_CHANGE';
export const GET_WEATHER_DATA_IN_PROGRESS = 'GET_WEATHER_DATA_IN_PROGRESS';
export const GET_WEATHER_DATA_SUCCESS = 'GET_WEATHER_DATA_SUCCESS';
export const GET_WEATHER_DATA_FAILED = 'GET_WEATHER_DATA_FAILED';
export const GET_WEATHER_HISTORY_DATA_IN_PROGRESS =
  'GET_WEATHER_HISTORY_DATA_IN_PROGRESS';
export const GET_WEATHER_HISTORY_DATA_SUCCESS =
  'GET_WEATHER_HISTORY_DATA_SUCCESS';
export const GET_WEATHER_HISTORY_DATA_FAILED =
  'GET_WEATHER_HISTORY_DATA_FAILED';
export const UPDATE_LOADING = 'UPDATE_LOADING';
